name: 'Terraform CI/CD Workflow'

on:
  push:
    branches:
      - master
  pull_request:

permissions:
  contents: read

env:
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

jobs:
  terraform-setup:
    name: 'Setup Azure Storage for Terraform'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set Up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.4.0

    - name: Terraform Init for Storage Setup
      run: |
        terraform init
        terraform apply -auto-approve -target=azurerm_resource_group.storage_rg -target=azurerm_storage_account.storage_account -target=azurerm_storage_container.state_container -target=azurerm_service_principal.service_principal -target=azurerm_role_assignment.sp_role_assignment

  terraform-test:
    name: 'Terraform Test'
    runs-on: ubuntu-latest
    needs: terraform-setup

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set Up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.4.0

    - name: Terraform Init
      run: terraform init

    - name: Terraform Validate
      run: terraform validate

  terraform-plan:
    name: 'Terraform Plan'
    runs-on: ubuntu-latest
    needs: terraform-test

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set Up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.4.0

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan -out=tfplan

    - name: Upload Terraform Plan to Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: terraform-plan
        path: tfplan

  terraform-apply:
    name: 'Terraform Apply'
    runs-on: ubuntu-latest
    needs: terraform-plan

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set Up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.4.0

    - name: Terraform Init
      run: terraform init

    - name: Download Terraform Plan
      uses: actions/download-artifact@v3
      with:
        name: terraform-plan
        path: ./

    - name: Terraform Apply
      run: terraform apply -auto-approve tfplan
